name: pytest

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: install poetry
        run: pip install poetry
      - name: Install dependencies
        run: make install
      - name: run lint
        run: make lint
      - name: run test
        run: make test
      - name: Create Reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.11.0-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter 
          ./cc-test-reporter before-build
      - name: run test cov
        run: make test-cov
      - name: Sending Repo
        env:
          GITHAB_TOKEN: ${{ secrets.TEST_REPORTER_ID }}
        run:  |
         ./cc-test-reporter after-build -r $GITHAB_TOKEN
